version: '3.8'

services:
  db:
    image: postgres:13
    container_name: notes_app_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./backend/auth-service
    container_name: auth_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/auth-service:/app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/app_db
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

  notes-service:
    build: ./backend/notes-service
    container_name: notes_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/notes-service:/app
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/app_db
      SECRET_KEY: ${SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - notes-service

volumes:
  postgres_data:
